name: Periodic health check

on:
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Heath check for for the delpoyed web app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fso-pokedex-ps.fly.dev/
          max-attempts: 5
          retry-delay: 10s