name: Periodic health check

on:
  push:
    branches:
      - main  
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  health-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Health check for for the delpoyed web app every day 5:30 UTC
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fso-pokedex-ps.fly.dev/
          max-attempts: 5
          retry-delay: 10s
      - name: Every time
        run: echo "Just checking"    